name: Go
on: [push, pull_request]
env:
  GO_VERSION: "1.20"
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Install Ginkgo CLI
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run tests
        run: |
          make test
